### ISSUE TITLE
[Bug]: rsbuild-plugin-tailwindcss introduces CSS properties that are not supported in Lynx.

### ISSUE THREAD

**Issue by xuanyi-fu** [lynx-family/lynx-stack#107]
### System Info

macOS

### Details

After importing Tailwind CSS into my project:

```typescript
import 'tailwindcss/utilities.css';
```

I encountered the following error in rspeedy:

```
lynx/ERROR [unit_handler.cc:182]: [0x1f9cb4f40:ERROR:unit_handler.cc(182)] [UnitHandler] css:position has invalid value static !!! It has be ignored.

lynx/ERROR [unit_handler.cc:182]: [0x1f9cb4f40:ERROR:unit_handler.cc(182)] [UnitHandler] css:display has invalid value inline !!! It has be ignored.

lynx/ERROR [unit_handler.cc:182]: [0x1f9cb4f40:ERROR:unit_handler.cc(182)] [UnitHandler] css:display has invalid value list-item !!! It has be ignored.
```

I searched the dist folder and found that main:background.css contains the following styles:

```css
.visible {
    visibility: visible;
}
.static {
    position: static;
}
.fixed {
    position: fixed;
}
.relative {
    position: relative;
}
.block {
    display: block;
}
.inline {
    display: inline;
}
.flex {
    display: flex;
}
.grid {
    display: grid;
}
.list-item {
    display: list-item;
}
.h-screen {
    height: 100vh;
}
.w-screen {
    width: 100vw;
}
.transform {
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) 
                rotate(var(--tw-rotate)) 
                skewX(var(--tw-skew-x)) 
                skewY(var(--tw-skew-y)) 
                scaleX(var(--tw-scale-x)) 
                scaleY(var(--tw-scale-y));
}
.bg-red-50 {
    --tw-bg-opacity: 1;
    background-color: rgb(254 242 242 / var(--tw-bg-opacity, 1));
}
.italic {
    font-style: italic;
}
.filter {
    filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) 
            var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) 
            var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow);
}
```

As seen in the generated CSS, properties such as position: static, display: block, and display: list-item are not supported in Lynx, but they still get bundled, leading to errors.

### Reproduce Steps

You can repro it using the project here:

[tailwind-css-lynx-error.zip](https://github.com/user-attachments/files/19117726/tailwind-css-lynx-error.zip)
